import type { GeneratedTheme, ExportFormat } from './types';

// ─── CSS Variables ─────────────────────────────────────────────────────────────

function toCssVariables(theme: GeneratedTheme): string {
  const { tokens, brandScale, neutralScale, config } = theme;

  const tokenLines = Object.entries(tokens)
    .map(([key, val]) => `  --color-${key}: ${val};`)
    .join('\n');

  const brandLines = Object.entries(brandScale)
    .map(([step, val]) => `  --color-brand-${step}: ${val};`)
    .join('\n');

  const neutralLines = Object.entries(neutralScale)
    .map(([step, val]) => `  --color-neutral-${step}: ${val};`)
    .join('\n');

  const configLines = [
    `  --radius-theme: ${config.radius};`,
    `  --font-family-theme: ${config.fontFamily};`,
    `  --font-heading-theme: ${config.headingFont};`,
    `  --base-font-size: ${config.baseSize};`,
  ].join('\n');

  return `:root {
  /* ── Primitives ── */
${configLines}

  /* ── Semantic Tokens ── */
${tokenLines}

  /* ── Brand Scale ── */
${brandLines}

  /* ── Neutral Scale ── */
${neutralLines}
}`;
}

// ─── JSON Design Tokens (W3C-style) ───────────────────────────────────────────

function toJsonTokens(theme: GeneratedTheme): string {
  const { tokens, brandScale, neutralScale, config } = theme;

  const semanticTokens: Record<string, { $value: string; $type: string }> = {};
  Object.entries(tokens).forEach(([key, val]) => {
    semanticTokens[key] = { $value: val, $type: 'color' };
  });

  const brandTokens: Record<string, { $value: string; $type: string }> = {};
  Object.entries(brandScale).forEach(([step, val]) => {
    brandTokens[step] = { $value: val, $type: 'color' };
  });

  const neutralTokens: Record<string, { $value: string; $type: string }> = {};
  Object.entries(neutralScale).forEach(([step, val]) => {
    neutralTokens[step] = { $value: val, $type: 'color' };
  });

  const configTokens = {
    radius: { $value: config.radius, $type: 'dimension' },
    fontFamily: { $value: config.fontFamily, $type: 'fontFamily' },
    headingFont: { $value: config.headingFont, $type: 'fontFamily' },
    baseSize: { $value: config.baseSize, $type: 'dimension' },
  };

  return JSON.stringify(
    {
      config: configTokens,
      color: {
        semantic: semanticTokens,
        brand: brandTokens,
        neutral: neutralTokens,
      },
    },
    null,
    2
  );
}

// ─── Tailwind Config ──────────────────────────────────────────────────────────

function toTailwindConfig(theme: GeneratedTheme): string {
  const { tokens, brandScale, neutralScale, config } = theme;

  const semanticEntries = Object.entries(tokens)
    .map(([key, val]) => `      '${key}': '${val}',`)
    .join('\n');

  const brandEntries = Object.entries(brandScale)
    .map(([step, val]) => `        '${step}': '${val}',`)
    .join('\n');

  const neutralEntries = Object.entries(neutralScale)
    .map(([step, val]) => `        '${step}': '${val}',`)
    .join('\n');

  return `/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        // Semantic tokens
${semanticEntries}
        // Brand scale
        brand: {
${brandEntries}
        },
        // Neutral scale
        neutral: {
${neutralEntries}
        },
      },
      borderRadius: {
        'theme': '${config.radius}',
      },
      fontFamily: {
        'theme': ['${config.fontFamily.split(',')[0].replace(/"/g, '')}', 'sans-serif'],
        'heading': ['${config.headingFont.split(',')[0].replace(/"/g, '')}', 'sans-serif'],
      }
    },
  },
};`;
}

// ─── Shopify Theme Settings ───────────────────────────────────────────────────

function toShopifyMapping(theme: GeneratedTheme): string {
  const { tokens, config } = theme;

  const settingsLines = Object.entries(tokens)
    .map(([key, val]) => `  "${key}": "${val}"`)
    .join(',\n');

  return `{
  "// Shopify theme settings_data.json mappings": "Generated by ThemeForge",
  "colors_solid_button_labels": "${tokens['cta-text']}",
  "colors_accent_1": "${tokens.brand}",
  "colors_accent_2": "${tokens.accent}",
  "colors_text": "${tokens.text}",
  "colors_background_1": "${tokens.background}",
  "colors_background_2": "${tokens.surface}",
  "buttons_radius": ${parseInt(config.radius) || 0},

  "// Full semantic token mapping": "",
${settingsLines}
}`;
}

// ─── Entry point ──────────────────────────────────────────────────────────────

export function formatExport(theme: GeneratedTheme, format: ExportFormat): string {
  switch (format) {
    case 'css': return toCssVariables(theme);
    case 'json': return toJsonTokens(theme);
    case 'tailwind': return toTailwindConfig(theme);
    case 'shopify': return toShopifyMapping(theme);
  }
}

export function getFileExtension(format: ExportFormat): string {
  switch (format) {
    case 'css': return 'css';
    case 'json': return 'json';
    case 'tailwind': return 'js';
    case 'shopify': return 'json';
  }
}

export function getFileName(format: ExportFormat, themeLabel: string): string {
  const slug = themeLabel.toLowerCase().replace(/\s+/g, '-');
  return `themeforge-${slug}.${getFileExtension(format)}`;
}
